# Site Settings
title: Marek Mahut
url: 'http://mmahut.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Marek Mahut
tagline: DevOps Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Devps Engineer with more than ten years of system administration experience. Focused on cloud computing,
automation and site reliability.'

#sidebar links
email: marek.mahut@gmail.com
phone: +420 739 636 703
linkedin: marekmahut
github: mmahut

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
